# login page
user_name_id = "username"
pwd_id_id = "password"
btn_id = "login"
loc_id_id = "location"
hotel_id_id = "hotels"
room_type_id = "room_type"
room_nos_id = "room_nos"
date_id_id = "datepick_in"
date_out_id = "datepick_out"
adult_room_id = "adult_room"
child_room_id = "child_room"
search_btn_id = "Submit"
sele_id_id = "radiobutton_0"
continue_btn_id = "continue"
#book hotel page
firstname_id="first_name"
laname_id="last_name"
card_no_id="cc_num"
card_type_id="cc_type"
month_ex_id="cc_exp_month"
ex_year_id="cc_exp_year"
cc_num_id="cc_cvv"
add_id_id="address"
book_id_id="book_now"
order_no_id = "order_no"